export const mockVideos = [
  {
    id: "1",
    videoId: "video1",
    title: "How to Build a Next.js Application",
    description: "Learn how to build a modern web application using Next.js 13 with App Router and Server Components.",
    publishedAt: new Date("2024-02-15"),
    thumbnailUrl: "https://i.ytimg.com/vi/1234567890/maxresdefault.jpg",
    channelId: "channel1",
    channelTitle: "Code Masters",
    viewCount: 15000,
    likeCount: 1200,
    dislikeCount: 10,
    commentCount: 150,
    userId: "user1",
  },
  {
    id: "2",
    videoId: "video2",
    title: "TypeScript Tips and Tricks for 2024",
    description: "Discover advanced TypeScript features and patterns that will make you a better developer.",
    publishedAt: new Date("2024-02-10"),
    thumbnailUrl: "https://i.ytimg.com/vi/0987654321/maxresdefault.jpg",
    channelId: "channel2",
    channelTitle: "TypeScript Guru",
    viewCount: 25000,
    likeCount: 2200,
    dislikeCount: 15,
    commentCount: 250,
    userId: "user1",
  },
  {
    id: "3",
    videoId: "video3",
    title: "Building a SaaS Application from Scratch",
    description: "Follow along as we build a complete SaaS application using modern web technologies.",
    publishedAt: new Date("2024-02-05"),
    thumbnailUrl: "https://i.ytimg.com/vi/5432109876/maxresdefault.jpg",
    channelId: "channel1",
    channelTitle: "Code Masters",
    viewCount: 35000,
    likeCount: 3200,
    dislikeCount: 20,
    commentCount: 350,
    userId: "user1",
  }
];

export const mockComments = [
  {
    id: "comment1",
    videoId: "1",
    userId: "user1",
    commentText: "This was incredibly helpful! I especially loved the section about server components.",
    likeCount: 50,
    dislikeCount: 0,
    publishedAt: new Date("2024-02-16"),
  },
  {
    id: "comment2",
    videoId: "1",
    userId: "user2",
    commentText: "Great tutorial! Could you make one about authentication in Next.js?",
    likeCount: 30,
    dislikeCount: 0,
    publishedAt: new Date("2024-02-15"),
  },
  {
    id: "comment3",
    videoId: "1",
    userId: "user3",
    commentText: "The explanations were very clear. Thanks for making this!",
    likeCount: 25,
    dislikeCount: 0,
    publishedAt: new Date("2024-02-14"),
  }
]; 